import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { documentPage, esc, billingUrl, contactUrl } from './layout.mjs';
import { resourcePages } from '../src/resource-data.js';
const source = JSON.parse(readFileSync(new URL('../source-evidence/functional-inventory.json', import.meta.url)));
const root = new URL('../', import.meta.url);
const write = (path, html) => { const dest = new URL(path, root); mkdirSync(new URL('./', dest), { recursive: true }); writeFileSync(dest, html); };
let home = readFileSync(new URL('../src/home.html', import.meta.url), 'utf8').replaceAll('{{calendarUrl}}', esc(source.calendarEmbedUrl)).replaceAll('{{billingUrl}}', billingUrl).replaceAll('{{contactUrl}}', contactUrl);
write('index.html', documentPage({title:'Artesia Country Club | Golf, Dining & Community in Artesia, NM',description:'Eighteen holes. A welcoming clubhouse. Your Artesia community since 1946. Explore golf, dining, club events, memberships and member resources.',body:home,home:true}));
const extras = [{slug:'course-map',title:'A new perspective on Artesia.',eyebrow:'The course map',description:'Explore the course layout, original aerial photograph, and course film credits.',sections:[{title:'The course, hole by hole',html:'<p>The club’s illustrated course guide, supplied as a reference. The diagram is a schematic and is not to scale.</p><a href="/images/course-layout.png" target="_blank" rel="noopener"><img class="course-map-image" src="/images/course-layout.png" width="339" height="354" alt="Illustrated Artesia Country Club layout showing holes 1 through 18, practice range and Pro Shop"></a><p><a href="/clubhouse-rules-1/">Read golf rules and course etiquette ↗</a></p>'},{title:'About the course film',html:'<p>The scroll experience is an AI-generated film based on photographs of Artesia Country Club. It imagines a low flight along the fairways, over the fountain pond, and toward the clubhouse.</p><p>Supplied photographs guide the appearance of the course, pond and clubhouse. The route between viewpoints and unseen details are generated. It is not recorded drone footage or an exact course walkthrough.</p>'},{title:'See the actual landscape',html:'<p>This unchanged USDA aerial photograph shows the real course and surrounding landscape on May 19, 2022. It was used to understand the setting. Current vegetation, water levels, and development may differ. The illustrated guide is a schematic and may also differ from this dated photograph.</p><a href="/images/course-aerial.jpg" target="_blank" rel="noopener"><img src="/images/course-aerial.jpg" width="3072" height="3072" loading="lazy" alt="2022 north-up USDA aerial photograph of the actual course and surrounding Artesia landscape"></a><p>Imagery: USDA NAIP, distributed by <a href="https://imagery.nationalmap.gov/arcgis/rest/services/USGSNAIPImagery/ImageServer" target="_blank" rel="noopener">USGS National Map</a>. Public-domain U.S. government data. Ask the Pro Shop for current playing information.</p>'}]}];
const pages = [...resourcePages,...extras];
for (const page of pages) {
  const index = page.sections.length > 3 ? `<nav class="page-index" aria-label="On this page"><p class="eyebrow">On this page</p>${page.sections.map((s,i)=>`<a href="#section-${i+1}">${esc(s.title || `Section ${i+1}`)}</a>`).join('')}</nav>` : '';
  const body = `<main id="main"${page.slug === "memberships" ? ' class="membership-page"' : ""}><div class="resource-hero container"><a href="/#resources" class="breadcrumb">← Back to the club</a><p class="eyebrow">${esc(page.eyebrow || 'Artesia Country Club')}</p><h1>${esc(page.title)}</h1><p>${esc(page.description || '')}</p></div><div class="reading-surface"><div class="container reading-layout">${index}<article class="resource-content">${page.sections.map((s,i)=>`<section id="section-${i+1}">${page.slug === "menu" || s.archived ? `<details class="content-disclosure" ${page.slug === "menu" && i === 0 ? "open" : ""}><summary><h2>${esc(s.title)}</h2><span aria-hidden="true">+</span></summary>${s.html}</details>` : `${s.title ? `<h2>${esc(s.title)}</h2>`:""}${s.html}`}</section>`).join('')}<div class="resource-help"><h2>We’re here to help.</h2><p>Questions about club information? Call <a href="tel:+15757462055">(575) 746-2055</a> or <a href="${contactUrl}" target="_blank" rel="noopener">send a message ↗</a>.</p>${page.sourceUrl ? `<a class="source-reference" href="${esc(page.sourceUrl.replace('https://www.artesiacc.com','https://sparrow-sheep-7aha.squarespace.com'))}" target="_blank" rel="noopener">View the club’s original page ↗</a>` : ''}</div></article></div></div></main>`;
  const html = documentPage({title:`${page.title} | Artesia Country Club`,description:page.description || `${page.title} at Artesia Country Club.`,path:`/${page.slug}/`,body});
  write(`${page.slug}/index.html`,html);
  for (const alias of page.aliases || []) write(`${alias}/index.html`,html);
}
const redirects = {'golf-2':'golf','tournaments':'events'};
for(const [from,to] of Object.entries(redirects)) write(`${from}/index.html`,documentPage({title:'Golf at Artesia Country Club',description:'Find golf and tournament information.',path:`/${to}/`,body:`<main id="main" class="container section-space"><h1>Golf at Artesia.</h1><p><a class="button" href="/${to}/">Continue to ${to} ↗</a></p></main>`}));
write('404.html', documentPage({title:'Page not found | Artesia Country Club',description:'Find your way back to Artesia Country Club.',body:'<main id="main" class="resource-hero container"><p class="eyebrow">A little off the fairway</p><h1>Let’s get you back.</h1><p>This page could not be found.</p><a class="button" href="/">Back to the club ↗</a></main>'}));
write('public/sitemap.xml',`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${['',...pages.map(p=>p.slug+'/')].map(p=>`<url><loc>https://www.artesiacc.com/${p}</loc></url>`).join('')}</urlset>`);
console.log(`Generated homepage, ${pages.length} content pages, source-path aliases, sitemap and 404.`);
